/* 主模块*/
var app=angular.module("onlineApp",["myControllerModule","ngCookies","ui.router","ui.grid","ui.grid.pagination","myServiceModule","ui.grid.selection"]);
//配置路由
app.config(function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise("login");
	$stateProvider.state("login",{
		url:"/login",
		views:{
			"index":{
				templateUrl:"templates/login.html"
			}
		}
	}).state("main",{
		url:"/main",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@main":{
				templateUrl:"templates/menu.html"
			}

		}
	}).state("allusers",{
		url:"/allusers",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@allusers":{
				templateUrl:"templates/menu.html"
			},
			"content@allusers":{
				templateUrl:"templates/allusers.html"
			}
		}
	}).state("addusers",{
		url:"/addusers",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@addusers":{
				templateUrl:"templates/menu.html"
			},
			"content@addusers":{
				templateUrl:"templates/addusers.html"
			}
		}
	}).state("searchusers",{
		url:"/searchusers",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@searchusers":{
				templateUrl:"templates/menu.html"
			},
			"content@searchusers":{
				templateUrl:"templates/searchusers.html"
			}

		}
	}).state("userdetail",{
		url:"/userdetail/:id",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@userdetail":{
				templateUrl:"templates/menu.html"
			},
			"content@userdetail":{
				templateUrl:"templates/userdetail.html"
			}
		}
	}).state("modify",{
		url:"/modify/:id",
		views:{
			"index":{
				templateUrl:"templates/main.html"
			},
			"menu@modify":{
				templateUrl:"templates/menu.html"
			},
			"content@modify":{
				templateUrl:"templates/modifyuser.html"
			}
		}
	});
});
